export const SYMPTOMS_CONSTANTS = {
  SYMPTOM_LIST: [
    { label: 'itching', name: 'itching' },
    { label: 'skin_rash', name: 'skin_rash' },
    { label: 'nodal_skin_eruptions', name: 'nodal_skin_eruptions' },
    { label: 'continuous_sneezing', name: 'continuous_sneezing' },
    { label: 'shivering', name: 'shivering' },
    { label: 'chills', name: 'chills' },
    { label: 'joint_pain', name: 'joint_pain' },
    { label: 'stomach_pain', name: 'stomach_pain' },
    { label: 'acidity', name: 'acidity' },
    { label: 'ulcers_on_tongue', name: 'ulcers_on_tongue' },
    { label: 'muscle_wasting', name: 'muscle_wasting' },
    { label: 'vomiting', name: 'vomiting' },
    { label: 'burning_micturition', name: 'burning_micturition' },
    { label: 'spotting_urination', name: 'spotting_urination' },
    { label: 'fatigue', name: 'fatigue' },
    { label: 'weight_gain', name: 'weight_gain' },
    { label: 'anxiety', name: 'anxiety' },
    { label: 'cold_hands_and_feets', name: 'cold_hands_and_feets' },
    { label: 'mood_swings', name: 'mood_swings' },
    { label: 'weight_loss', name: 'weight_loss' },
    { label: 'restlessness', name: 'restlessness' },
    { label: 'lethargy', name: 'lethargy' },
    { label: 'patches_in_throat', name: 'patches_in_throat' },
    { label: 'irregular_sugar_level', name: 'irregular_sugar_level' },
    { label: 'cough', name: 'cough' },
    { label: 'high_fever', name: 'high_fever' },
    { label: 'sunken_eyes', name: 'sunken_eyes' },
    { label: 'breathlessness', name: 'breathlessness' },
    { label: 'sweating', name: 'sweating' },
    { label: 'dehydration', name: 'dehydration' },
    { label: 'indigestion', name: 'indigestion' },
    { label: 'headache', name: 'headache' },
    { label: 'yellowish_skin', name: 'yellowish_skin' },
    { label: 'dark_urine', name: 'dark_urine' },
    { label: 'nausea', name: 'nausea' },
    { label: 'loss_of_appetite', name: 'loss_of_appetite' },
    { label: 'pain_behind_the_eyes', name: 'pain_behind_the_eyes' },
    { label: 'back_pain', name: 'back_pain' },
    { label: 'constipation', name: 'constipation' },
    { label: 'abdominal_pain', name: 'abdominal_pain' },
    { label: 'diarrhoea', name: 'diarrhoea' },
    { label: 'mild_fever', name: 'mild_fever' },
    { label: 'yellow_urine', name: 'yellow_urine' },
    { label: 'yellowing_of_eyes', name: 'yellowing_of_eyes' },
    { label: 'acute_liver_failure', name: 'acute_liver_failure' },
    { label: 'fluid_overload', name: 'fluid_overload' },
    { label: 'swelling_of_stomach', name: 'swelling_of_stomach' },
    { label: 'swelled_lymph_nodes', name: 'swelled_lymph_nodes' },
    { label: 'malaise', name: 'malaise' },
    {
      label: 'blurred_and_distorted_vision',
      name: 'blurred_and_distorted_vision',
    },
    { label: 'phlegm', name: 'phlegm' },
    { label: 'throat_irritation', name: 'throat_irritation' },
    { label: 'redness_of_eyes', name: 'redness_of_eyes' },
    { label: 'sinus_pressure', name: 'sinus_pressure' },
    { label: 'runny_nose', name: 'runny_nose' },
    { label: 'congestion', name: 'congestion' },
    { label: 'chest_pain', name: 'chest_pain' },
    { label: 'weakness_in_limbs', name: 'weakness_in_limbs' },
    { label: 'fast_heart_rate', name: 'fast_heart_rate' },
    {
      label: 'pain_during_bowel_movements',
      name: 'pain_during_bowel_movements',
    },
    { label: 'pain_in_anal_region', name: 'pain_in_anal_region' },
    { label: 'bloody_stool', name: 'bloody_stool' },
    { label: 'irritation_in_anus', name: 'irritation_in_anus' },
    { label: 'neck_pain', name: 'neck_pain' },
    { label: 'dizziness', name: 'dizziness' },
    { label: 'cramps', name: 'cramps' },
    { label: 'bruising', name: 'bruising' },
    { label: 'obesity', name: 'obesity' },
    { label: 'swollen_legs', name: 'swollen_legs' },
    { label: 'swollen_blood_vessels', name: 'swollen_blood_vessels' },
    { label: 'puffy_face_and_eyes', name: 'puffy_face_and_eyes' },
    { label: 'enlarged_thyroid', name: 'enlarged_thyroid' },
    { label: 'brittle_nails', name: 'brittle_nails' },
    { label: 'swollen_extremeties', name: 'swollen_extremeties' },
    { label: 'excessive_hunger', name: 'excessive_hunger' },
    { label: 'extra_marital_contacts', name: 'extra_marital_contacts' },
    { label: 'drying_and_tingling_lips', name: 'drying_and_tingling_lips' },
    { label: 'slurred_speech', name: 'slurred_speech' },
    { label: 'knee_pain', name: 'knee_pain' },
    { label: 'hip_joint_pain', name: 'hip_joint_pain' },
    { label: 'muscle_weakness', name: 'muscle_weakness' },
    { label: 'stiff_neck', name: 'stiff_neck' },
    { label: 'swelling_joints', name: 'swelling_joints' },
    { label: 'movement_stiffness', name: 'movement_stiffness' },
    { label: 'spinning_movements', name: 'spinning_movements' },
    { label: 'loss_of_balance', name: 'loss_of_balance' },
    { label: 'unsteadiness', name: 'unsteadiness' },
    { label: 'weakness_of_one_body_side', name: 'weakness_of_one_body_side' },
    { label: 'loss_of_smell', name: 'loss_of_smell' },
    { label: 'bladder_discomfort', name: 'bladder_discomfort' },
    { label: 'foul_smell_of', name: 'foul_smell_of urine' },
    { label: 'continuous_feel_of_urine', name: 'continuous_feel_of_urine' },
    { label: 'passage_of_gases', name: 'passage_of_gases' },
    { label: 'internal_itching', name: 'internal_itching' },
    { label: 'toxic_look_', name: 'toxic_look_(typhos)' },
    { label: 'depression', name: 'depression' },
    { label: 'irritability', name: 'irritability' },
    { label: 'muscle_pain', name: 'muscle_pain' },
    { label: 'altered_sensorium', name: 'altered_sensorium' },
    { label: 'red_spots_over_body', name: 'red_spots_over_body' },
    { label: 'belly_pain', name: 'belly_pain' },
    { label: 'abnormal_menstruation', name: 'abnormal_menstruation' },
    { label: 'dischromic', name: 'dischromic _patches' },
    { label: 'watering_from_eyes', name: 'watering_from_eyes' },
    { label: 'increased_appetite', name: 'increased_appetite' },
    { label: 'polyuria', name: 'polyuria' },
    { label: 'family_history', name: 'family_history' },
    { label: 'mucoid_sputum', name: 'mucoid_sputum' },
    { label: 'rusty_sputum', name: 'rusty_sputum' },
    { label: 'lack_of_concentration', name: 'lack_of_concentration' },
    { label: 'visual_disturbances', name: 'visual_disturbances' },
    {
      label: 'receiving_blood_transfusion',
      name: 'receiving_blood_transfusion',
    },
    {
      label: 'receiving_unsterile_injections',
      name: 'receiving_unsterile_injections',
    },
    { label: 'coma', name: 'coma' },
    { label: 'stomach_bleeding', name: 'stomach_bleeding' },
    { label: 'distention_of_abdomen', name: 'distention_of_abdomen' },
    {
      label: 'history_of_alcohol_consumption',
      name: 'history_of_alcohol_consumption',
    },
    { label: 'fluid_overload', name: 'fluid_overload' },
    { label: 'blood_in_sputum', name: 'blood_in_sputum' },
    { label: 'prominent_veins_on_calf', name: 'prominent_veins_on_calf' },
    { label: 'palpitations', name: 'palpitations' },
    { label: 'painful_walking', name: 'painful_walking' },
    { label: 'pus_filled_pimples', name: 'pus_filled_pimples' },
    { label: 'blackheads', name: 'blackheads' },
    { label: 'scurring', name: 'scurring' },
    { label: 'skin_peeling', name: 'skin_peeling' },
    { label: 'silver_like_dusting', name: 'silver_like_dusting' },
    { label: 'small_dents_in_nails', name: 'small_dents_in_nails' },
    { label: 'inflammatory_nails', name: 'inflammatory_nails' },
    { label: 'blister', name: 'blister' },
    { label: 'red_sore_around_nose', name: 'red_sore_around_nose' },
    { label: 'yellow_crust_ooze', name: 'yellow_crust_ooze' },
  ],
};
